### ISSUE TITLE
Caused by: java.net.SocketException: Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by Nagy0** [Nepitwin/RabbitSSL#1]
I'm trying to connect to rabbitMQ over SSL using Spring Boot 2.7.4 and java 11.0.14

I have added the following configurations:

```
properties file:
rabbit.username=admin
rabbit.password=admin
rabbit.host=localhost
rabbit.port=5671
rabbit.ssl=TLSv1.2
rabbit.keystore.name=client_key.p12
rabbit.keystore.password=rabbitstore
rabbit.truststore=server_store.jks
rabbit.truststore.password=rabbitstore

```
```
Configuration class:

@Configuration
@PropertySource("classpath:rabbit.properties")
public class RabbitConfiguration {

    /**
     * Default sample channel name to respond for requests from clients.
     */
    public static final String DEFAULT_QUEUE = "sample_queue";

    /**
     * Environment properties file from rabbitmq configuration.
     */
    @Autowired
    private Environment env;

    /**
     * Establish a connection to a rabbit mq server.
     * @return Rabbit connection factory for rabbitmq access.
     * @throws IOException If wrong parameters are used for connection.
     */
    @Bean
    public RabbitConnectionFactoryBean connectionFactoryBean() throws IOException {
        RabbitConnectionFactoryBean connectionFactoryBean = new RabbitConnectionFactoryBean();
        connectionFactoryBean.setHost(Objects.requireNonNull(env.getProperty("rabbit.host")));
        connectionFactoryBean.setPort(Integer.parseInt(Objects.requireNonNull(env.getProperty("rabbit.port"))));
        connectionFactoryBean.setUsername(Objects.requireNonNull(env.getProperty("rabbit.username")));
        connectionFactoryBean.setPassword(Objects.requireNonNull(env.getProperty("rabbit.password")));

        // SSL-Configuration if set
        if(env.getProperty("rabbit.ssl") != null) {
            connectionFactoryBean.setUseSSL(true);
            connectionFactoryBean.setSslAlgorithm(Objects.requireNonNull(env.getProperty("rabbit.ssl")));

            // This information should be stored safely !!!
            connectionFactoryBean.setKeyStore(Objects.requireNonNull(env.getProperty("rabbit.keystore.name")));
            connectionFactoryBean.setKeyStorePassphrase(Objects.requireNonNull(env.getProperty("rabbit.keystore.password")));
            connectionFactoryBean.setTrustStore(Objects.requireNonNull(env.getProperty("rabbit.truststore")));
            connectionFactoryBean.setTrustStorePassphrase(Objects.requireNonNull(env.getProperty("rabbit.truststore.password")));
        }

        return connectionFactoryBean;
    }

    /**
     * Connection factory which established a rabbitmq connection used from a connection factory
     * @param connectionFactoryBean Connection factory bean to create connection.
     * @return A connection factory to create connections.
     * @throws Exception If wrong parameters are used for connection.
     */
    @Bean(name = "GEO_RABBIT_CONNECTION")
    public ConnectionFactory connectionFactory(RabbitConnectionFactoryBean connectionFactoryBean) throws Exception {
        return new CachingConnectionFactory(Objects.requireNonNull(connectionFactoryBean.getObject()));
    }

    /**
     * Queue initialization from rabbitmq to listen a queue.
     * @return An queue to listen for listen receiver.
     */
    @Bean
    public Queue queue() {
        // Create an new queue to handle incoming responds
        return new Queue(DEFAULT_QUEUE, false, false, false, null);
    }

    /**
     * Generates a simple message listener container.
     * @param connectionFactory Established connection to rabbitmq server.
     * @param listenerAdapter   Listener event adapter to listen for messages.
     * @return A simple message container for listening for requests.
     */
    @Bean
    public SimpleMessageListenerContainer container(ConnectionFactory connectionFactory,
                                                    MessageListenerAdapter listenerAdapter) {

        SimpleMessageListenerContainer container = new SimpleMessageListenerContainer();
        container.setConnectionFactory(connectionFactory);
        container.setQueueNames(DEFAULT_QUEUE);
        container.setMessageListener(listenerAdapter);
        container.setAcknowledgeMode(AcknowledgeMode.AUTO);
        return container;

    }

    /**
     * Message listener adapter to generate a message listener.
     * @param deviceMonitoringReceiver Device receive to for listening.
     * @return A message listener adapter to receive messages.
     */
    @Bean
    public MessageListenerAdapter listenerAdapter(DeviceMonitoringReceiver deviceMonitoringReceiver) {
        return new MessageListenerAdapter(deviceMonitoringReceiver, "receiveMessage");
    }
}
```
Also I have updated rabbitMQ configurations:

```
[
  {rabbit, [
     {ssl_listeners, [5671]},
     {ssl_options, [{cacertfile, "D:\\tls-gen\\basic\\result\\ca_certificate.pem"},
                    {certfile,   "D:\\tls-gen\\basic\\result\\server_seliiwvdec53152_certificate.pem"},
                    {keyfile,    "D:\\tls-gen\basic\\result\\server_seliiwvdec53152_key.pem"},
                    {verify,     verify_peer},
                    {fail_if_no_peer_cert, true}]}

   ]}
].
```

But the application is not starting and throwing

`Caused by: java.net.SocketException: Connection reset by peer: socket write error`

**Comment by Nepitwin** [comment]
If i run all examples by dockerized rabbitmq server instance the example does work and i don't get any connection reset by peer connections by java 11 and spring boot 2.7.4.

If i see is that you try to use a local running rabbitmq server on a windows host which is fine. But could probably force the issues because of this environment.

Could you potential test by docker-compose usage if the examples are working?

Then it is a first approach that a potential missconfiguration is used by rabbitmq because you use the old rabbitmq configuration syntax. New syntax can be found under Docker -> Config -> rabbitmq.conf

See asweel [The New and Old Config File Formats](https://www.rabbitmq.com/configure.html#config-file-formats)

Did you check rabbitmq server logs if server is correctly started and does not contain any certifates issues?

**Comment by Nagy0** [comment]
Yeah the problem is that we have the rabbitmq server running on windows host, So I need to making it works as it's.

I have tried the new syntax for rabbitmq configurations, But still no changes. Also the server logs don't have any errors everything is normal and I can see the TLS is enabled.

```
2022-12-21 16:28:48.357000+02:00 [info] <0.584.0> started TLS (SSL) listener on [::]:5671
2022-12-21 16:28:48.360000+02:00 [info] <0.604.0> started TLS (SSL) listener on 0.0.0.0:5671
```

**Comment by Nepitwin** [comment]
Which kind of rabbitmq server did you install? I would try to reproduce the issue to install the latest rabbitmq version installer by windows. Then i should reproduce the issue and try to identify what the issue is and to extend an windows based example which is currently missing.

https://www.rabbitmq.com/install-windows.html

**Comment by Nagy0** [comment]
I'm on Rabbitmq 3.11.5 and Erlang 25.2.

**Comment by Nagy0** [comment]
I resolved the issue by adding this to the configurations:

`ssl_options.password = xxx`
It's mentioned in the official documentation it's optional I don't know why. But whatever the issue is now resolved.

**Comment by Nepitwin** [comment]
Okay then it's fine thanks for the reply. Did you cipher your ssl keys by an additional password? If yes then it's clear that you need to use this configuration parameter or do you simple let it empty?

If the key is not ciphered by an additional key then this parameter should be obsolete.

**Comment by Nagy0** [comment]
I'm not sure about it I have generated the certificates/keys following this example here https://www.rabbitmq.com/ssl.html#automated-certificate-generation

So I'm not sure it's ciphered or not? is it?

**Comment by Nepitwin** [comment]
By this example your private key will from tls-gen generated an encrypted private key.

Which is stored with your password to decipher. Yes then you have to use this parameter.

On my example all keys does not have an additional cipher password for the rsa key.

Example for an encrypted private key

-----BEGIN ENCRYPTED PRIVATE KEY-----

Example for an private key without password

-----BEGIN RSA PRIVATE KEY-----

I generate the examples without a password.

Now i should reproduce the issue if i produce some test data with an ciphered password from private key which should be the default use case.
